version: '3'

services:

  server:
    build: ./server
    ports:
      -"8000:8000"
    depends_on:
      - storage
      - metadata_databse
      - video_processing_service
      - broker

  storage:
    build: ./storage
    volumes:
            - ./config/default.conf:/etc/nginx/conf.d/default.conf
            - ./shared_folder:/usr/share/nginx/html
    ports:
      - "7000:80"

  metadata_databse:
    build: ./metadata_databse
  
  broker:
    build: ./broker

  proxy:
    build: ./proxy
    volumes:
            - ./config/default.conf:/etc/nginx/conf.d/default.conf
            - ./shared_folder:/usr/share/nginx/html
    depends_on:
      - server

  video_processing_service:
    build: ./video_processing_service
    depends_on:
      - broker
      - storage
  
